import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by scripts/generate-icons.ts
    "src/generated/**",
    "packages/energy-icons/src/icons/**",
    "packages/energy-icons/src/index.ts",
    "packages/energy-icons/src/registry.ts",
    "packages/energy-icons/dist/**",
    "packages/energy-icons/svg/**",
    // Built by scripts/build-figma-plugin.ts
    "packages/figma-plugin/dist/**",
  ]),
]);

export default eslintConfig;
