/**
 * Builds packages/energy-icons from /icons:
 *   src/icons/<slug>.tsx     one component, one icon (tree-shaken import)
 *   src/index.ts             re-exports every component
 *   src/registry.ts          name → component map for energy-icons/icon
 *   svg/<slug>/              the source SVG files
 *
 * Run with `npm run package` (it also typechecks and emits dist/).
 */
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";

import { getMasterFileName, ICON_MASTERS, type IconMaster, type IconWeight } from "../src/config/icons";
import { icons } from "../src/data/icons";
import { parseSvg } from "../src/lib/icons/svg";

const ROOT = path.resolve(__dirname, "..");
const ICONS_DIR = path.join(ROOT, "icons");
const PKG = path.join(ROOT, "packages/energy-icons");
const SRC = path.join(PKG, "src");
const OUT_ICONS = path.join(SRC, "icons");
const OUT_SVG = path.join(PKG, "svg");

const toPascal = (slug: string) =>
  slug
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");

function artwork(slug: string, weight: IconWeight, master: IconMaster) {
  const file = path.join(ICONS_DIR, slug, getMasterFileName(master, weight));
  const source = readFileSync(file, "utf8");
  const parsed = parseSvg(source);
  return { viewBox: parsed.attributes.viewBox ?? "", body: parsed.body };
}

rmSync(OUT_ICONS, { recursive: true, force: true });
rmSync(OUT_SVG, { recursive: true, force: true });
mkdirSync(OUT_ICONS, { recursive: true });
mkdirSync(OUT_SVG, { recursive: true });

const seen = new Map<string, string>();
const indexLines: string[] = [];
const registryLines: string[] = [];
const importLines: string[] = [];

for (const icon of icons) {
  const component = toPascal(icon.slug);
  const previous = seen.get(component);
  if (previous) throw new Error(`Component name ${component} is used by both "${previous}" and "${icon.slug}"`);
  if (component === "Icon") throw new Error(`Slug "${icon.slug}" would export Icon, which is the dynamic component`);
  seen.set(component, icon.slug);

  const fields = ICON_MASTERS.map((master) => {
    const drawn = artwork(icon.slug, "regular", master);
    return `    ${master}: { viewBox: ${JSON.stringify(drawn.viewBox)}, body: ${JSON.stringify(drawn.body)} },`;
  });

  const hasBold = ICON_MASTERS.every((master) => existsSync(path.join(ICONS_DIR, icon.slug, getMasterFileName(master, "bold"))));
  let boldBlock = "";
  if (hasBold) {
    const boldFields = ICON_MASTERS.map((master) => {
      const drawn = artwork(icon.slug, "bold", master);
      return `    ${master}: { viewBox: ${JSON.stringify(drawn.viewBox)}, body: ${JSON.stringify(drawn.body)} },`;
    });
    boldBlock = `,\n  bold: {\n${boldFields.join("\n")}\n  }`;
  }

  const source = `// Generated by scripts/build-package.ts. Do not edit.
import { createIcon } from "../create-icon.js";

export const ${component} = createIcon(${JSON.stringify(icon.slug)}, {
  regular: {
${fields.join("\n")}
  }${boldBlock},
});
`;
  writeFileSync(path.join(OUT_ICONS, `${icon.slug}.tsx`), source);

  const destDir = path.join(OUT_SVG, icon.slug);
  mkdirSync(destDir, { recursive: true });
  for (const weight of ["regular", "bold"] as const) {
    if (weight === "bold" && !hasBold) continue;
    for (const master of ICON_MASTERS) {
      const filename = getMasterFileName(master, weight);
      cpSync(path.join(ICONS_DIR, icon.slug, filename), path.join(destDir, filename));
    }
  }

  indexLines.push(`export { ${component} } from "./icons/${icon.slug}.js";`);
  importLines.push(`import { ${component} } from "./icons/${icon.slug}.js";`);
  registryLines.push(`  ${JSON.stringify(icon.slug)}: ${component},`);
}

writeFileSync(
  path.join(SRC, "index.ts"),
  `// Generated by scripts/build-package.ts. Do not edit.
${indexLines.join("\n")}
export type { IconComponentProps as IconProps, IconWeight } from "./types.js";
`,
);

writeFileSync(
  path.join(SRC, "registry.ts"),
  `// Generated by scripts/build-package.ts. Do not edit.
${importLines.join("\n")}

export const icons = {
${registryLines.join("\n")}
} as const;
`,
);

console.log(`✓ energy-icons package source: ${icons.length} icons → packages/energy-icons`);
